config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views import defaults as default_views

from xiaoyuanwen.news.views import NewsListView


urlpatterns = [
    path("", NewsListView.as_view(), name="home"),
    path("admin/", admin.site.urls),

    # 用户管理
    path("users/", include("xiaoyuanwen.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),

    # 开发的应用
    path('news/', include('xiaoyuanwen.news.urls', namespace="news")),
    path('articles/', include('xiaoyuanwen.articles.urls', namespace="articles")),
    path('qa/', include('xiaoyuanwen.qa.urls', namespace="qa")),
    path('messager/', include('xiaoyuanwen.messager.urls', namespace="messager")),
    path('notifications/', include('xiaoyuanwen.notifications.urls', namespace="notifications")),

    # 第三方应用
    path('markdownx/', include('markdownx.urls')),
    path('comments/', include('django_comments.urls')),
    path('search/', include('haystack.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

xiaoyuanwen/articles/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from xiaoyuanwen.articles import views


app_name = 'articles'

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='list'),
    path('write-new-article/', views.ArticleCreateView.as_view(), name='write_new'),
    path('drafts/', views.DraftListView.as_view(), name='drafts'),
    path('<str:slug>/', cache_page(60 * 5)(views.ArticleDetailView.as_view()), name='article'),
    path('edit/<int:pk>/', views.ArticleEditView.as_view(), name='edit_article'),
    path("delete/<int:pk>/", views.ArticleDeleteView.as_view(), name="delete_article"),
]

xiaoyuanwen/news/urls.py
from django.urls import path

from xiaoyuanwen.news import views


app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path("post-news/", views.post_news, name="post_news"),
    path("delete/<str:pk>/", views.NewsDeleteView.as_view(), name="delete_news"),
    path("like/", views.like, name="like_post"),
    path("get-thread/", views.get_thread, name="get_thread"),
    path("post-comment/", views.post_comment, name="post_comments"),
    path("update-interactions/", views.update_interactions, name='update_interactions'),
]

xiaoyuanwen/qa/urls.py
from django.urls import path

from xiaoyuanwen.qa import views


app_name = 'qa'

urlpatterns = [
    path('', views.UnansweredQuestionListView.as_view(), name="unanswered_q"),
    path('answered/', views.AnsweredQuestionListView.as_view(), name="answered_q"),
    path('indexed/', views.QuestionListView.as_view(), name="all_q"),
    path('ask-question/', views.CreateQuestionView.as_view(), name="ask_question"),
    path('question-detail/<int:pk>/', views.QuestionDetailView.as_view(), name="question_detail"),
    path('propose-answer/<int:question_id>/', views.CreateAnswerView.as_view(), name="propose_answer"),
    path('question/vote/', views.question_vote, name="question_vote"),
    path('answer/vote/', views.answer_vote, name="answer_vote"),
    path('accept-answer/', views.accept_answer, name='accept_answer'),
]

xiaoyuanwen/users/urls.py
from django.urls import path

from xiaoyuanwen.users import views

app_name = "users"

urlpatterns = [
    path("update/", views.UserUpdateView.as_view(), name="update"),
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

xiaoyuanwen/articles/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from xiaoyuanwen.articles.models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    edited = forms.BooleanField(widget=forms.HiddenInput(), initial=False, required=False)
    content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ['title', 'content', 'image', 'tags', 'status', 'edited']

xiaoyuanwen/qa/forms.py
from django import forms
from markdownx.fields import MarkdownxFormField

from xiaoyuanwen.qa.models import Question


class QuestionForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    content = MarkdownxFormField()

    class Meta:
        model = Question
        fields = ["title", "content", "tags", "status"]

xiaoyuanwen/articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from django_comments.signals import comment_was_posted

from xiaoyuanwen.articles.models import Article
from xiaoyuanwen.articles.forms import ArticleForm
from xiaoyuanwen.helpers import AuthorRequireMixin
from xiaoyuanwen.notifications.views import notification_handler


class ArticlesListView(LoginRequiredMixin, ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 10
    context_object_name = "articles"
    template_name = "articles/article_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self):
        return Article.objects.get_published()


class DraftListView(ArticlesListView):
    """草稿箱中的文章列表"""
    def get_queryset(self):
        return Article.objects.filter(user=self.request.user).get_drafts()


@method_decorator(cache_page(60 * 60), name='get')
class ArticleCreateView(LoginRequiredMixin, CreateView):
    """发表文章"""
    model = Article
    form_class = ArticleForm
    template_name = "articles/article_create.html"
    message = "您的文章已发表成功！"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("articles:list")


class ArticleDetailView(LoginRequiredMixin, DetailView):
    """文章详情"""
    model = Article
    template_name = 'articles/article_detail.html'

    def get_queryset(self):
        return Article.objects.select_related('user').filter(slug=self.kwargs['slug'])


class ArticleEditView(LoginRequiredMixin, AuthorRequireMixin, UpdateView):
    """编辑文章"""
    model = Article
    form_class = ArticleForm
    template_name = "articles/article_update.html"
    message = "您的文章编辑成功！"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("articles:article", kwargs={'slug': self.get_object().slug})


class ArticleDeleteView(LoginRequiredMixin, AuthorRequireMixin, DeleteView):
    """删除文章"""
    model = Article
    template_name = 'articles/article_confirm_delete.html'
    message = "您的文章删除成功！"

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("articles:list")


def notify_comment(**kwargs):
    """文章有评论时通知文章作者"""
    actor = kwargs['request'].user
    obj = kwargs['comment'].content_object
    if actor.username != obj.user.username:
        notification_handler(actor, obj.user, 'C', obj)


comment_was_posted.connect(receiver=notify_comment)

xiaoyuanwen/messager/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from django.template.loader import render_to_string
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from xiaoyuanwen.messager.models import Message
from xiaoyuanwen.helpers import ajax_required
from xiaoyuanwen.notifications.views import notification_handler


class MessagesListView(LoginRequiredMixin, ListView):
    """所有用户的私信列表"""
    model = Message
    template_name = "messager/message_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        """获取除当前登录用户外的所有用户"""
        context = super(MessagesListView, self).get_context_data()
        context["users_list"] = get_user_model().objects.filter(is_active=True).exclude(
            username=self.request.user
        ).order_by('-last_login')[:8]
        last_conversation = Message.objects.get_most_recent_conversation(self.request.user)
        context["active"] = last_conversation.username
        return context

    def get_queryset(self):
        """最近私信互动的内容"""
        active_user = Message.objects.get_most_recent_conversation(self.request.user)
        return Message.objects.get_conversation(active_user, self.request.user)


class ConversationListView(MessagesListView):
    """与指定用户的私信内容"""
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ConversationListView, self).get_context_data()
        context["active"] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_object_or_404(get_user_model(), username=self.kwargs["username"])
        return Message.objects.get_conversation(active_user, self.request.user)


@login_required
@ajax_required
@require_http_methods(["POST"])
def send_message(request):
    """私信聊天"""
    sender = request.user
    recipient_username = request.POST["to"]
    recipient = get_user_model().objects.get(username=recipient_username)
    message = request.POST["message"]
    if len(message.strip()) != 0 and sender != recipient:
        msg = Message.objects.create(
            sender=sender,
            recipient=recipient,
            message=message
        )
        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            'message': render_to_string('messager/single_message.html', {'message': msg}),
            'sender': sender.username
        }
        async_to_sync(channel_layer.group_send)(recipient_username, payload)
        notification_handler(sender, recipient, 'R', msg)
        return render(request, 'messager/single_message.html', {"message": msg})
    return HttpResponse()

xiaoyuanwen/news/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DeleteView
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.urls import reverse_lazy

from xiaoyuanwen.news.models import News
from xiaoyuanwen.helpers import ajax_required, AuthorRequireMixin


class NewsListView(LoginRequiredMixin, ListView):
    """动态列表"""
    model = News
    paginate_by = 20
    template_name = 'news/news_list.html'

    def get_queryset(self):
        return News.objects.filter(reply=False).select_related('user', 'parent').prefetch_related('liked')


class NewsDeleteView(LoginRequiredMixin, AuthorRequireMixin, DeleteView):
    """删除动态"""
    model = News
    template_name = 'news/news_confirm_delete.html'
    message = "您的动态删除成功！"

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("news:list")


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_news(request):
    """发表动态（AJAX POST）"""
    post = request.POST['post'].strip()
    if post:
        posted = News.objects.create(user=request.user, content=post)
        html = render_to_string('news/news_single.html', {'news': posted, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞动态（AJAX POST）"""
    news_id = request.POST['news']
    news = News.objects.get(pk=news_id)
    news.switch_like(request.user)
    return JsonResponse({'likes': news.liked_count()})


@login_required
@ajax_required
@require_http_methods(['GET'])
def get_thread(request):
    """返回动态的评论（AJAX GET）"""
    news_id = request.GET['news']
    news = News.objects.select_related('user').get(pk=news_id)
    news_html = render_to_string('news/news_single.html', {'news': news})
    thread_html = render_to_string('news/news_thread.html', {'thread': news.get_thread()})
    return JsonResponse({
        "uuid": news_id,
        "news": news_html,
        "thread": thread_html
    })


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_comment(request):
    """发表评论（AJAX POST）"""
    post = request.POST['reply'].strip()
    parent_id = request.POST['parent']
    parent = News.objects.get(pk=parent_id)
    if post:
        parent.reply_this(request.user, post)
        return JsonResponse({'comments': parent.comment_count()})
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def update_interactions(request):
    """更新互动信息（AJAX POST）"""
    date_point = request.POST['id_value']
    news = News.objects.get(pk=date_point)
    return JsonResponse({'likes': news.liked_count(), 'comments': news.comment_count()})

xiaoyuanwen/notifications/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView
from channels.layers import get_channel_layer
from asgiref.sync import async_to_sync

from xiaoyuanwen.notifications.models import Notification


class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """未读通知列表"""
    model = Notification
    context_object_name = "notification_list"
    template_name = "notifications/notification_list.html"

    def get_queryset(self, **kwargs):
        return self.request.user.notifications.unread()


@login_required
def get_latest_notifications(request):
    """最近的未读通知"""
    notifications = request.user.notifications.get_most_recent()
    return render(request, 'notifications/most_recent.html', {'notifications': notifications})


@login_required
def mark_as_read(request, slug):
    """将某条通知标为已读"""
    notification = get_object_or_404(Notification, slug=slug)
    notification.mark_as_read()
    if request.META.get('HTTP_REFERER'):
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('notifications:unread')


@login_required
def mark_all_as_read(request):
    """将所有通知标为已读"""
    request.user.notifications.mark_all_as_read()
    if request.META.get('HTTP_REFERER'):
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('notifications:unread')


def notification_handler(actor, recipient, verb, action_object, **kwargs):
    """
    通知处理器
    :param actor: request.user对象
    :param recipient: User Instance 接收者实例，一个或多个接收者
    :param verb: str 通知类别
    :param action_object: Instance 动作对象的实例
    :param kwargs: key, id_value等
    :return: None
    """
    key = kwargs.get('key', 'notification')
    id_value = kwargs.get('id_value', None)
    Notification.objects.create(
        actor=actor,
        recipient=recipient,
        verb=verb,
        action_object=action_object
    )
    channel_layer = get_channel_layer()
    if action_object.__class__.__name__ == 'Message':
        action_object_username = action_object.sender.username
    else:
        action_object_username = action_object.user.username
    payload = {
        'type': 'receive',
        'key': key,
        'actor_name': actor.username,
        'action_object': action_object_username,
        'id_value': id_value
    }
    async_to_sync(channel_layer.group_send)('notifications', payload)

xiaoyuanwen/templates/articles/article_confirm_delete.html
{% extends "base.html" %}

{% block head_title %}删除文章{% endblock %}

{% block content %}

    <h3>确定要删除该篇文章吗？</h3>

    <form method="post" action="{% url 'articles:delete_article' article.pk %}">
        {% csrf_token %}
        <button class="btn btn-danger" type="submit">删除</button>
    </form>

{% endblock %}

xiaoyuanwen/templates/articles/article_create.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}写文章 - {{ block.super }}{% endblock %}
{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'articles:list' %}">文章</a></li>
            <li class="breadcrumb-item active" aria-current="page">写文章</li>
        </ol>
    </nav>
    <form action="{% url 'articles:write_new' %}" enctype="multipart/form-data" id="article-form" method="post" role="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="button" class="btn btn-primary publish">发表</button>
            <button type="button" class="btn btn-default draft">保存草稿</button>
            <a class="btn btn-light" style="float:right" href="{% url 'articles:list' %}">取消</a>
        </div>
    </form>
    {{ form.media }}

{% endblock content %}

{% block js %}
    <script src="{% static 'js/articles.js' %}"></script>
{% endblock js %}

xiaoyuanwen/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load static comments crispy_forms_tags thumbnail %}

{% block title %}{{ article.title|title }} - {{ block.super }}{% endblock %}

{% block css %}
    <link href="{% static 'css/article.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
                <li class="breadcrumb-item"><a href="{% url 'articles:list' %}">文章</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ article.title|title }}</li>
            </ol>
        </nav>
        <div class="row">
            <!-- Post Content Column -->
            <div class="col-lg-8">
                <!-- Title -->
                <h2 class="text-center">{{ article.title|title }}</h2>
                <!-- Author -->
                <p class="text-left">
                    <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name }}</a>
                    发表于{{ article.created_at }}
                </p>
                <hr>
                <!-- 文章图片 -->
                {% thumbnail article.image "1920x1080" as im %}
                    <img src="{{ im.url }}" alt="文章图片" class="card-img-top">
                {% empty %}
                    <img class="img-fluid rounded" src="http://placehold.it/1920x1080" alt="Card Image">
                {% endthumbnail %}
                <hr>
                <!-- Post Content -->
                <p class="card-text">{{ article.get_markdown|safe }}</p>
                <hr>
                <!-- Comments Form -->
                <div class="card my-4">
                    <h5 class="card-header">评论</h5>
                    <div class="card-body">
                        {% if user.is_authenticated %}
                            {% get_comment_form for article as form %}
                            <form action="{% comment_form_target %}" method="POST">
                               {% csrf_token %}
                               <div id="id_comment" class="form-group">
                                   <textarea name="comment" rows="5" maxlength="400" class="textarea form-control"></textarea>
                               </div>
                               {{ form.content_type }}
                               {{ form.object_pk }}
                               {{ form.timestamp }}
                               {{ form.security_hash }}
                               <input type="hidden" name="next" value="{% url 'articles:article' article.slug %}"/>
                               <input class="btn btn-info" type="submit" value="提交" id="id_submit"/>
                            </form>
                        {% endif %}
                    </div>
                </div>

                <!-- Single Comment -->
                {% get_comment_list for article as comment_list %}
                {% for comment in comment_list %}
                    <div class="media mb-4">
                        {% thumbnail comment.user.picture "x50" as im %}
                            <img src="{{ im.url }}" class="user-image" style="border-radius: 50%;" alt="用户头像">
                        {% empty %}
                            <img src="{% static 'img/user.png' %}" class="user-image" style="border-radius: 50%;" height="50px" alt="没有头像"/>
                        {% endthumbnail %}
                        <div class="media-body">
                            <a href="{% url 'users:detail' comment.user.username %}" class="username">{{ comment.user.get_profile_name }}</a>
                            <small class="comment">评论于 {{ comment.submit_date|timesince }}之前</small>
                            <p>&nbsp;{{ comment.comment }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>

            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Write Article Widget -->
                {% if request.user.is_authenticated %}
                    <div class="card my-4">
                        <div class="card-body text-center">
                            <a class="btn btn-success" href="{% url 'articles:write_new' %}" title="写文章">
                                <i class="fa fa-pencil" aria-hidden="true"></i> 写文章</a>

                            {% if request.user.username == article.user.username %}
                                <a class="btn btn-primary" href="{% url 'articles:edit_article' article.id %}" title="编辑文章">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 编辑</a>
                                <a class="btn btn-danger" href="{% url 'articles:delete_article' article.id %}" title="删除文章">
                                    <i class="fa fa-trash" aria-hidden="true"></i> 删除文章</a>
                            {% endif %}

                        </div>
                    </div>
                {% endif %}
                <!-- 云标签 -->
                <div class="card my-4">
                    <h5 class="card-header">云标签</h5>
                    <div class="card-body">
                        {% for tag in article.tags.all %}
                            <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock content %}

xiaoyuanwen/templates/articles/article_list.html
{% extends 'base.html' %}
{% load static thumbnail %}

{% block title %}文章 - {{ block.super }}{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
                <li class="breadcrumb-item active"><a href="{% url 'articles:list' %}">文章</a></li>
            </ol>
        </nav>
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                {% for article in articles %}
                    <!-- Blog Post -->
                    <div class="card mb-4">
                        {% thumbnail article.image "1920x1080" as im %}
                            <img src="{{ im.url }}" alt="文章图片" class="card-img-top">
                        {% empty %}
                            <img class="card-img-top" src="http://placehold.it/1920x1080" alt="图片大小">
                        {% endthumbnail %}

                        <div class="card-body">
                            <h3 class="card-title">{{ article.title|title }}</h3>
                            <p class="">{{ article.get_markdown|safe|truncatechars:100 }}</p>
                        </div>
                        <div class="card-footer text-muted">
                            <a href="{% url 'users:detail' article.user.username %}">{{ article.user.get_profile_name }}</a>
                            发表于{{ article.created_at }}

                            {% for tag in article.tags.names %}
                                <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
                            {% endfor %}
                            <a style="float:right" href="{% url 'articles:article' article.slug %}" class="btn-sm btn-primary">阅读全文→</a>
                        </div>
                    </div>
                    {% empty %}
                    <h4 class="no-data"><a href="{% url 'articles:write_new' %}">快来成为第一个写文章的吧！</a></h4>
                {% endfor %}

                {% include 'pagination.html' %}

            </div>

            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Write Article Widget -->
                {% if request.user.is_authenticated %}
                    <div class="card my-4">
                        <div class="card-body text-center">
                            <a class="btn btn-success" href="{% url 'articles:write_new' %}" title="写文章">
                                <i class="fa fa-pencil" aria-hidden="true"></i> 写文章</a>
                            <a class="btn btn-primary" href="{% url 'articles:drafts' %}" title="草稿箱">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> 草稿箱</a>
                        </div>
                    </div>
                {% endif %}
                <!-- 云标签 -->
                <div class="card my-4">
                    <h5 class="card-header">云标签</h5>
                    <div class="card-body">
                        {% for tag, count in popular_tags %}
                            <a href="#"><span class="badge badge-info">{{ tag }}({{ count }})</span></a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->

{% endblock content %}

xiaoyuanwen/templates/articles/article_update.html
{% extends 'base.html' %}
{% load static crispy_forms_tags %}
{% block title %}更新文章 - {{ block.super }}{% endblock %}

{% block content %}

    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'news:list' %}">首页</a></li>
            <li class="breadcrumb-item"><a href="{% url 'articles:drafts' %}">草稿箱</a></li>
            <li class="breadcrumb-item active" aria-current="page">更新文章</li>
        </ol>
    </nav>
    <form action="{% url 'articles:edit_article' form.instance.pk %}" enctype="multipart/form-data" id="article-form" method="post" role="form">
        {% csrf_token %}
        {{ form|crispy }}
        <div class="form-group">
            <button type="button" class="btn btn-primary update">更新</button>
            <button type="button" class="btn btn-default draft">保存草稿</button>
            <a href="{% url 'articles:drafts' %}" class="btn btn-default">取消</a>
        </div>
    </form>
    {{ form.media }}

{% endblock content %}

{% block js %}
    <script src="{% static 'js/articles.js' %}"></script>
{% endblock js %}