config/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.views import defaults as default_views

from xiaoyuanwen.news.views import NewsListView


urlpatterns = [
    path("", NewsListView.as_view(), name="home"),
    path("admin/", admin.site.urls),

    # 用户管理
    path("users/", include("xiaoyuanwen.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),

    # 开发的应用
    path('news/', include('xiaoyuanwen.news.urls', namespace="news")),
    path('articles/', include('xiaoyuanwen.articles.urls', namespace="articles")),
    path('qa/', include('xiaoyuanwen.qa.urls', namespace="qa")),
    path('messager/', include('xiaoyuanwen.messager.urls', namespace="messager")),
    path('notifications/', include('xiaoyuanwen.notifications.urls', namespace="notifications")),

    # 第三方应用
    path('markdownx/', include('markdownx.urls')),
    path('comments/', include('django_comments.urls')),
    path('search/', include('haystack.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

xiaoyuanwen/news/urls.py
from django.urls import path

from xiaoyuanwen.news import views


app_name = "news"

urlpatterns = [
    path("", views.NewsListView.as_view(), name="list"),
    path("post-news/", views.post_news, name="post_news"),
    path("delete/<str:pk>/", views.NewsDeleteView.as_view(), name="delete_news"),
    path("like/", views.like, name="like_post"),
    path("get-thread/", views.get_thread, name="get_thread"),
    path("post-comment/", views.post_comment, name="post_comments"),
    path("update-interactions/", views.update_interactions, name='update_interactions'),
]

xiaoyuanwen/qa/urls.py
from django.urls import path

from xiaoyuanwen.qa import views


app_name = 'qa'

urlpatterns = [
    path('', views.UnansweredQuestionListView.as_view(), name="unanswered_q"),
    path('answered/', views.AnsweredQuestionListView.as_view(), name="answered_q"),
    path('indexed/', views.QuestionListView.as_view(), name="all_q"),
    path('ask-question/', views.CreateQuestionView.as_view(), name="ask_question"),
    path('question-detail/<int:pk>/', views.QuestionDetailView.as_view(), name="question_detail"),
    path('propose-answer/<int:question_id>/', views.CreateAnswerView.as_view(), name="propose_answer"),
    path('question/vote/', views.question_vote, name="question_vote"),
    path('answer/vote/', views.answer_vote, name="answer_vote"),
    path('accept-answer/', views.accept_answer, name='accept_answer'),
]

xiaoyuanwen/users/urls.py
from django.urls import path

from xiaoyuanwen.users import views

app_name = "users"

urlpatterns = [
    path("update/", views.UserUpdateView.as_view(), name="update"),
    path("<str:username>/", views.UserDetailView.as_view(), name="detail"),
]

xiaoyuanwen/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class User(AbstractUser):
    """自定义用户模型"""
    GENDER_CHOICE = (
        ('male', '男'),
        ('female', '女')
    )
    COLLEGE_CHOICE = (
        ('tx', '通信与信息工程学院'),
        ('jxj', '计算机科学与技术学院'),
        ('zdh', '自动化学院'),
        ('xj', '先进制造工程学院'),
        ('gd', '光电工程学院/重庆国际半导体学院'),
        ('rj', '软件工程学院'),
        ('sw', '生物信息学院'),
        ('l', '理学院'),
        ('jg', '经济管理学院/现代邮政学院'),
        ('cm', '传媒艺术学院'),
        ('wgy', '外国语学院'),
        ('gj', '国际学院'),
        ('af', '网络空间安全与信息法学院'),
        ('mks', '马克思主义学院'),
        ('ty', '体育学院'),
    )
    LOCATION_CHOICE = (
        ('bj', '北京'),
        ('tj', '天津'),
        ('hb1', '河北'),
        ('sx1', '山西'),
        ('nmg', '内蒙古'),
        ('ln', '辽宁'),
        ('jl', '吉林'),
        ('hlj', '黑龙江'),
        ('sh', '上海'),
        ('js', '江苏'),
        ('zj', '浙江'),
        ('ah', '安徽'),
        ('fj', '福建'),
        ('jx', '江西'),
        ('sd', '山东'),
        ('henan', '河南'),
        ('hb2', '湖北'),
        ('hn1', '湖南'),
        ('gd', '广东'),
        ('gx', '广西'),
        ('hn2', '海南'),
        ('cq', '重庆'),
        ('sc', '四川'),
        ('gz', '贵州'),
        ('yn', '云南'),
        ('xz', '西藏'),
        ('sx2', '陕西'),
        ('gs', '甘肃'),
        ('qh', '青海'),
        ('nx', '宁夏'),
        ('xj', '新疆'),
        ('tw', '台湾'),
        ('xg', '香港特别行政区'),
        ('am', '澳门特别行政区'),
        ('hw', '海外'),
    )

    nickname = models.CharField(max_length=6, null=True, blank=True, verbose_name='昵称')
    gender = models.CharField(choices=GENDER_CHOICE, max_length=10, null=True, blank=True, verbose_name='性别')
    picture = models.ImageField(upload_to='profile_pics/', null=True, blank=True, verbose_name='头像')
    stu_id = models.PositiveIntegerField(unique=True, null=True, blank=True, verbose_name='学号')
    grade = models.CharField(max_length=4, null=True, blank=True, verbose_name='年级')
    college = models.CharField(choices=COLLEGE_CHOICE, max_length=20, null=True, blank=True, verbose_name='学院')
    location = models.CharField(choices=LOCATION_CHOICE, max_length=10, null=True, blank=True, verbose_name='家乡')
    introduction = models.CharField(max_length=20, default='这位同学很懒，还没有编辑个人简介',
                                    null=True, blank=True, verbose_name='个人简介')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def get_profile_name(self):
        if self.nickname:
            return self.nickname
        return self.username

xiaoyuanwen/articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from django_comments.signals import comment_was_posted

from xiaoyuanwen.articles.models import Article
from xiaoyuanwen.articles.forms import ArticleForm
from xiaoyuanwen.helpers import AuthorRequireMixin
from xiaoyuanwen.notifications.views import notification_handler


class ArticlesListView(LoginRequiredMixin, ListView):
    """已发布的文章列表"""
    model = Article
    paginate_by = 10
    context_object_name = "articles"
    template_name = "articles/article_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self):
        return Article.objects.get_published()


class DraftListView(ArticlesListView):
    """草稿箱中的文章列表"""
    def get_queryset(self):
        return Article.objects.filter(user=self.request.user).get_drafts()


@method_decorator(cache_page(60 * 60), name='get')
class ArticleCreateView(LoginRequiredMixin, CreateView):
    """发表文章"""
    model = Article
    form_class = ArticleForm
    template_name = "articles/article_create.html"
    message = "您的文章已发表成功！"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("articles:list")


class ArticleDetailView(LoginRequiredMixin, DetailView):
    """文章详情"""
    model = Article
    template_name = 'articles/article_detail.html'

    def get_queryset(self):
        return Article.objects.select_related('user').filter(slug=self.kwargs['slug'])


class ArticleEditView(LoginRequiredMixin, AuthorRequireMixin, UpdateView):
    """编辑文章"""
    model = Article
    form_class = ArticleForm
    template_name = "articles/article_update.html"
    message = "您的文章编辑成功！"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("articles:article", kwargs={'slug': self.get_object().slug})


class ArticleDeleteView(LoginRequiredMixin, AuthorRequireMixin, DeleteView):
    """删除文章"""
    model = Article
    template_name = 'articles/article_confirm_delete.html'
    message = "您的文章删除成功！"

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("articles:list")


def notify_comment(**kwargs):
    """文章有评论时通知文章作者"""
    actor = kwargs['request'].user
    obj = kwargs['comment'].content_object
    if actor.username != obj.user.username:
        notification_handler(actor, obj.user, 'C', obj)


comment_was_posted.connect(receiver=notify_comment)

xiaoyuanwen/messager/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.decorators.http import require_http_methods
from django.views.generic import ListView
from django.template.loader import render_to_string
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer

from xiaoyuanwen.messager.models import Message
from xiaoyuanwen.helpers import ajax_required
from xiaoyuanwen.notifications.views import notification_handler


class MessagesListView(LoginRequiredMixin, ListView):
    """所有用户的私信列表"""
    model = Message
    template_name = "messager/message_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        """获取除当前登录用户外的所有用户"""
        context = super(MessagesListView, self).get_context_data()
        context["users_list"] = get_user_model().objects.filter(is_active=True).exclude(
            username=self.request.user
        ).order_by('-last_login')[:8]
        last_conversation = Message.objects.get_most_recent_conversation(self.request.user)
        context["active"] = last_conversation.username
        return context

    def get_queryset(self):
        """最近私信互动的内容"""
        active_user = Message.objects.get_most_recent_conversation(self.request.user)
        return Message.objects.get_conversation(active_user, self.request.user)


class ConversationListView(MessagesListView):
    """与指定用户的私信内容"""
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ConversationListView, self).get_context_data()
        context["active"] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_object_or_404(get_user_model(), username=self.kwargs["username"])
        return Message.objects.get_conversation(active_user, self.request.user)


@login_required
@ajax_required
@require_http_methods(["POST"])
def send_message(request):
    """私信聊天"""
    sender = request.user
    recipient_username = request.POST["to"]
    recipient = get_user_model().objects.get(username=recipient_username)
    message = request.POST["message"]
    if len(message.strip()) != 0 and sender != recipient:
        msg = Message.objects.create(
            sender=sender,
            recipient=recipient,
            message=message
        )
        channel_layer = get_channel_layer()
        payload = {
            'type': 'receive',
            'message': render_to_string('messager/single_message.html', {'message': msg}),
            'sender': sender.username
        }
        async_to_sync(channel_layer.group_send)(recipient_username, payload)
        notification_handler(sender, recipient, 'R', msg)
        return render(request, 'messager/single_message.html', {"message": msg})
    return HttpResponse()

xiaoyuanwen/news/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DeleteView
from django.template.loader import render_to_string
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.urls import reverse_lazy

from xiaoyuanwen.news.models import News
from xiaoyuanwen.helpers import ajax_required, AuthorRequireMixin


class NewsListView(LoginRequiredMixin, ListView):
    """动态列表"""
    model = News
    paginate_by = 20
    template_name = 'news/news_list.html'

    def get_queryset(self):
        return News.objects.filter(reply=False).select_related('user', 'parent').prefetch_related('liked')


class NewsDeleteView(LoginRequiredMixin, AuthorRequireMixin, DeleteView):
    """删除动态"""
    model = News
    template_name = 'news/news_confirm_delete.html'
    message = "您的动态删除成功！"

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse_lazy("news:list")


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_news(request):
    """发表动态（AJAX POST）"""
    post = request.POST['post'].strip()
    if post:
        posted = News.objects.create(user=request.user, content=post)
        html = render_to_string('news/news_single.html', {'news': posted, 'request': request})
        return HttpResponse(html)
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def like(request):
    """点赞动态（AJAX POST）"""
    news_id = request.POST['news']
    news = News.objects.get(pk=news_id)
    news.switch_like(request.user)
    return JsonResponse({'likes': news.liked_count()})


@login_required
@ajax_required
@require_http_methods(['GET'])
def get_thread(request):
    """返回动态的评论（AJAX GET）"""
    news_id = request.GET['news']
    news = News.objects.select_related('user').get(pk=news_id)
    news_html = render_to_string('news/news_single.html', {'news': news})
    thread_html = render_to_string('news/news_thread.html', {'thread': news.get_thread()})
    return JsonResponse({
        "uuid": news_id,
        "news": news_html,
        "thread": thread_html
    })


@login_required
@ajax_required
@require_http_methods(['POST'])
def post_comment(request):
    """发表评论（AJAX POST）"""
    post = request.POST['reply'].strip()
    parent_id = request.POST['parent']
    parent = News.objects.get(pk=parent_id)
    if post:
        parent.reply_this(request.user, post)
        return JsonResponse({'comments': parent.comment_count()})
    else:
        return HttpResponseBadRequest("内容不能为空！")


@login_required
@ajax_required
@require_http_methods(['POST'])
def update_interactions(request):
    """更新互动信息（AJAX POST）"""
    date_point = request.POST['id_value']
    news = News.objects.get(pk=date_point)
    return JsonResponse({'likes': news.liked_count(), 'comments': news.comment_count()})

xiaoyuanwen/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    """用户详情页"""
    model = User
    template_name = "users/user_detail.html"
    slug_field = "username"
    slug_url_kwarg = "username"

    def get_context_data(self, **kwargs):
        """统计用户个人数据"""
        context = super(UserDetailView, self).get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user.username)
        context['moments_num'] = user.publisher.filter(reply=False).count()
        context['article_num'] = user.author.filter(status='P').count()
        context['comment_num'] = user.publisher.filter(reply=True).count() + user.comment_comments.all().count()
        context['question_num'] = user.q_author.all().count()
        context['answer_num'] = user.a_author.all().count()

        sent_users = user.sent_messages.all()  # 当前用户给哪些用户发送过私信
        receive_users = user.received_messages.all()  # 当前用户接收过来自哪些用户的私信
        sent_users_set = set()
        receive_users_set = set()
        for s in sent_users:
            sent_users_set.add(s.recipient.username)
        for r in receive_users:
            receive_users_set.add(r.sender.username)
        tmp = sent_users_set & receive_users_set
        context['interaction_num'] = user.liked_news.all().count() + user.qa_vote.all().count() + \
                                     context['comment_num'] + len(tmp)
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    """更新用户个人信息"""
    model = User
    fields = ["nickname", "gender", "picture", "stu_id", "grade", "college", "location", "introduction", ]
    template_name = "users/user_form.html"

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self, queryset=None):
        return self.request.user

xiaoyuanwen/templates/users/user_detail.html
{% extends "base.html" %}
{% load static thumbnail %}

{% block title %}{{ object.username }} - {{ block.super }}{% endblock %}

{% block css %}
    <link href="{% static 'css/user_profile.css' %}" rel="stylesheet">
{#  <script src="https://kit.fontawesome.com/" crossorigin="anonymous"></script>  替换自己的kit，否则图标丢失#}
{% endblock css %}

{% block content %}
    <div class="row">
        <div class="profile-picture">
            {% thumbnail object.picture "x180" as im %}
                <img src="{{ im.url }}" class="user-image pull-left" style="border-radius: 50%;" alt="用户头像">
            {% empty %}
                <img src="{% static 'img/user.png' %}" class="user-image pull-left" style="border-radius: 50%;" height="180px" alt="没有头像"/>
            {% endthumbnail %}
        </div>

        <div class="col-md-7">
            <div class="card card-body"><p>{{ object.introduction }}</p></div>
        </div>
        <div class="col-md-3">
            <i class="fas fa-user-circle" aria-hidden="true"></i>&nbsp;{{ object.get_profile_name }}<br/>
            <i class="fas fa-envelope" aria-hidden="true"></i><a class="email" href="mailto:{{ object.email }}">&nbsp;{{ object.email }}</a><br/>
            {% if object.gender %}
                <i class="fas fa-venus-mars" aria-hidden="true"></i>&nbsp;{{ object.get_gender_display }}<br/>
            {% endif %}
            {% if object.stu_id %}
                <i class="fas fa-address-card" aria-hidden="true"></i>&nbsp;{{ object.stu_id }}<br/>
            {% endif %}
            {% if object.grade %}
                <i class="fas fa-user-graduate" aria-hidden="true"></i>&nbsp;{{ object.grade }}<br/>
            {% endif %}
            {% if object.college %}
                <i class="fas fa-university" aria-hidden="true"></i>&nbsp;{{ object.get_college_display }}<br/>
            {% endif %}
            {% if object.location %}
                <i class="fas fa-home" aria-hidden="true"></i>&nbsp;{{ object.get_location_display }}<br/>
            {% endif %}
            <div class="mb-2"></div>
            <!--自己的页面显示更新按钮-->
            {% if request.user.username == object.username %}
                <a class="btn btn-primary" href="{% url 'users:update' %}">更新信息</a>
            {% endif %}
        </div>
    </div>

    <div class="clear mb-3"></div>

    {% if request.user.username == object.username %}
        <!-- Data tiles -->
        <div class="row tile_count">
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-code"> 动态</p>
                <div class="count">{{ moments_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-key"> 文章</p>
                <div class="count">{{ article_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-comments"> 评论</p>
                <div class="count">{{ comment_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-question-circle"> 提问</p>
                <div class="count">{{ question_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-keyboard"> 回答</p>
                <div class="count">{{ answer_num }}</div>
            </div>
            <div class="col-md-2 col-sm-3 col-xs-4 tile_stats_count">
                <p class="fa fa-navicon"> 互动</p>
                <div class="count">{{ interaction_num }}</div>
            </div>
        </div>
        <!-- /data tiles -->
    {% endif %}
{% endblock content %}

xiaoyuanwen/templates/users/user_form.html
{% extends "base.html" %}
{% load static crispy_forms_tags thumbnail %}

{% block title %}用户信息 - {{ block.super }}{% endblock %}

{% block css %}
    <link href="{% static 'css/user_form.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

    <div class="row profile">
        <div class="col-md-3">
            <div style="font-size: 2em; font-weight: bold">&emsp;&nbsp;&nbsp;{{ user.username }}</div>
            <div class="profile-picture">
                {% thumbnail object.picture "x180" as im %}
                    <img src="{{ im.url }}" class="user-image pull-left" style="border-radius: 50%;" alt="用户头像">
                {% empty %}
                    <img src="{% static 'img/user.png' %}" class="user-image pull-left" style="border-radius: 50%;" height="180px" alt="没有头像"/>
                {% endthumbnail %}
            </div>
        </div>

        <div class="col-md-9">
            <form enctype="multipart/form-data" class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                    <div class="controls">
                        <button type="submit" class="btn btn-primary">更新</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}